version: '3.8'
services:
  mongodb:
    image: mongo:5.0.15
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: product_batch_db
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb

volumes:
  mongodb_data:

